Repository 2025-Summer-Bootcamp-TeamA/backend, pull requests merged in 2025-07, with the labels that each got.

#2 set: 젠킨스 ci
  Jenkinsfile
Labels: ⚙️ Setting

#8 feat: 영상 자동 저장
  Dockerfile
  apps/posts/urls.py
  apps/videos/__init__.py
  apps/videos/admin.py
  apps/videos/apps.py
  apps/videos/migrations/0001_initial.py
  apps/videos/migrations/__init__.py
  apps/videos/models.py
  apps/videos/serializers.py
  apps/videos/tests.py
  apps/videos/urls.py
  apps/videos/views.py
  config/settings/base.py
  config/urls.py
Labels: ✨ Feature

#16 [feat/#14] google OAuth 로그인
  apps/authentication/__init__.py
  apps/authentication/admin.py
  apps/authentication/apps.py
  apps/authentication/migrations/__init__.py
  apps/authentication/models.py
  apps/authentication/serializers.py
  apps/authentication/tests.py
  apps/authentication/urls.py
  apps/authentication/views.py
  config/settings.py
  config/settings/base.py
  config/urls.py
Labels: ✨ Feature

#18 [Feat/#12]영상목록조회
  .github/ISSUE_TEMPLATE/feat.md
  apps/videos/migrations/0002_video_user.py
  apps/videos/models.py
  apps/videos/serializers.py
  apps/videos/urls.py
  apps/videos/views.py
  config/settings.py
  pyproject.toml
  uv.lock
Labels: ✨ Feature

#24 [feat/#11] 영상 생성
  .gitignore
  apps/authentication/urls.py
  apps/avatars/admin.py
  apps/avatars/urls.py
  apps/avatars/views.py
  apps/core/__init__.py
  apps/core/facades/__init__.py
  apps/core/facades/video_creation_facade.py
  apps/core/services/__init__.py
  apps/core/services/entities/__init__.py
  apps/core/services/entities/artwork_basic_info.py
  apps/core/services/entities/artwork_extracted_info.py
  apps/core/services/entities/content_fetch_info.py
  apps/core/services/entities/extraction_metadata.py
  apps/core/services/entities/video_script_info.py
  apps/core/services/entities/web_search_info.py
  apps/core/services/externals/__init__.py
  apps/core/services/externals/brave_service.py
  apps/core/services/externals/fetch_service.py
  apps/core/services/externals/gemini_service.py
  apps/core/services/ocr_service.py
  apps/core/services/usecases/__init__.py
  apps/core/services/usecases/artwork_info_orchestrator.py
  apps/core/services/usecases/basic_artwork_extractor.py
  apps/core/services/usecases/content_fetch_enricher.py
  apps/core/services/usecases/video_script_generator.py
  apps/core/services/usecases/web_search_enricher.py
  apps/core/services/video_service.py
  apps/gcs/__init__.py
  apps/gcs/apps.py
  apps/gcs/storage_service.py
  apps/posts/admin.py
  apps/posts/models.py
  apps/posts/tests.py
  apps/posts/urls.py
  apps/posts/views.py
  apps/videos/__init__.py
  apps/videos/serializers/__init__.py
  apps/videos/serializers/video_serializer.py
  apps/videos/services/__init__.py
  apps/videos/services/video_generator.py
  apps/videos/services/visionstory_service.py
  apps/videos/services/visionstory_video_generator.py
  apps/videos/services/visionstory_video_info.py
  apps/videos/urls.py
  apps/videos/views/__init__.py
  apps/videos/views/video_creation_view.py
  apps/videos/views/video_crud_views.py
  config/settings.py
  config/settings/base.py
  config/settings/dev.py
  config/urls.py
  pyproject.toml
  uv.lock
Labels: ✨ Feature

#31 [Fix/#30] 도커빌드오류해결
  Dockerfile
  apps/place/urls.py
  apps/posts/urls.py
  apps/videos/urls.py
  config/settings.py
  config/urls.py
  docker-compose.yml
  pyproject.toml
  uv.lock
Labels: 👾 Bug

#33 [Fix/#32] pip 설정, visionstory 영상 목록 조회
  .gitignore
  .uvrc
  Dockerfile
  Makefile
  README.md
  apps/core/services/usecases/video_script_generator.py
  apps/videos/urls.py
  apps/videos/views/visionstory_latest_view.py
  config/urls.py
  docker-compose.yml
  pyproject.toml
  requirements-dev.txt
  requirements-prod.txt
  requirements.txt
  uv.lock
Labels: 👾 Bug, ⚙️ Setting, ✨ Feature

#36 [refactor/#35] 엔드포인트 수정
  apps/authentication/urls.py
  apps/authentication/views.py
  apps/avatars/views.py
  apps/place/views.py
  apps/videos/urls.py
  apps/videos/views/video_creation_view.py
  apps/videos/views/video_crud_views.py
  apps/videos/views/visionstory_latest_view.py
  config/urls.py
Labels: 🛠️ Refactor

#40 [setting/#39] traefik
  docker-compose.prod.yml
  docker-compose.yml
Labels: ⚙️ Setting

#42 [setting/#39] https 도메인 추가
  docker-compose.prod.yml
Labels: ⚙️ Setting

#44 [setting/#39] https 라우팅
  config/settings/prod.py
  config/urls.py
Labels: ⚙️ Setting

#46 [setting/#39] https
  config/settings/prod.py
  config/urls.py
  docker-compose.prod.yml
Labels: ⚙️ Setting

#41 [feat/#29] 비동기처리 작업 연동 및 구글맵스mcp 오류 수정
  .dockerignore
  Dockerfile
  apps/core/apps.py
  apps/core/tasks.py
  apps/place/admin.py
  apps/place/serializers.py
  apps/place/services/maps_mcp.py
  apps/place/tests.py
  apps/place/urls.py
  apps/place/views.py
  config/__init__.py
  config/celery.py
  config/settings/base.py
  config/urls.py
  docker-compose.prod.yml
  docker-compose.yml
  pyproject.toml
  requirements.txt
Labels: ✨ Feature, 🛠️ Refactor

#47 Feat/#43 Google Cloud Vision OCR API 구현
  .dockerignore
  .gitignore
  apps/core/services/ocr_service.py
  apps/core/urls.py
  apps/core/views.py
  config/urls.py
  docker-compose.yml
  requirements.txt
Labels: ✨ Feature

#57 [feat/#50] 영상 db 저장, 배포 모니터링
  apps/core/services/externals/fetch_service.py
  apps/core/services/usecases/content_fetch_enricher.py
  apps/core/services/usecases/web_search_enricher.py
  apps/place/views.py
  apps/videos/migrations/0002_remove_duration_field.py
  apps/videos/migrations/0003_video_museum_name.py
  apps/videos/migrations/0004_alter_video_thumbnail_url_alter_video_video_url.py
  apps/videos/migrations/0005_video_description.py
  apps/videos/models.py
  apps/videos/serializers/video_serializer.py
  apps/videos/views/video_creation_view.py
  apps/videos/views/video_viewset.py
  config/__init__.py
  docker-compose.prod.yml
  docker-compose.yml
  grafana/data/alerting/1/__default__.tmpl
  grafana/data/grafana.db
  prometheus/prometheus.yml
Labels: ⚙️ Setting, ✨ Feature
